spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/support_platform}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true

logging:
  level:
    com.supportplatform: DEBUG
