package com.supportplatform.storage;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * Tenant-scoped file metadata (storage-domain.md §2) — bytes live in
 * object storage, never in Postgres (Rule 2: Postgres holds facts about
 * the world, not the world's bulk data). The FK to {@code Message} lives
 * here, not on {@code Message}, so linking an attachment to a message
 * needs no ALTER on a table every prior phase already depends on.
 *
 * <p>Id is application-assigned ({@code UUID.randomUUID()}), not
 * {@code @UuidGenerator} — the object key embeds the attachment's own
 * id (storage-domain.md §2), so the id has to exist before the row
 * does, not be handed back by an insert.
 */
@Entity
@Table(name = "attachment")
@EntityListeners(AuditingEntityListener.class)
public class Attachment {

    @Id
    private UUID id;

    @Column(name = "tenant_id", nullable = false)
    private UUID tenantId;

    @Column(name = "message_id")
    private UUID messageId;

    @Column(name = "object_key", nullable = false, length = 500)
    private String objectKey;

    @Column(name = "content_type", nullable = false)
    private String contentType;

    @Column(name = "file_name")
    private String fileName;

    @Column(name = "size_bytes", nullable = false)
    private long sizeBytes;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected Attachment() {
    }

    /** {@code id} is generated by the caller, not here — it has to be known before this constructor runs, to build the object key it's embedded in (storage-domain.md §2). */
    public Attachment(UUID id, UUID tenantId, String objectKey, String contentType, String fileName, long sizeBytes) {
        this.id = id;
        this.tenantId = tenantId;
        this.objectKey = objectKey;
        this.contentType = contentType;
        this.fileName = fileName;
        this.sizeBytes = sizeBytes;
    }

    /** One-way: once linked, an attachment stays linked — WhatsApp's own model has no notion of reusing one across messages. */
    public void linkToMessage(UUID messageId) {
        this.messageId = messageId;
    }

    public UUID getId() {
        return id;
    }

    public UUID getTenantId() {
        return tenantId;
    }

    public UUID getMessageId() {
        return messageId;
    }

    public String getObjectKey() {
        return objectKey;
    }

    public String getContentType() {
        return contentType;
    }

    public String getFileName() {
        return fileName;
    }

    public long getSizeBytes() {
        return sizeBytes;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
